package com.deppon.foss.dubbo.crm.api.define.masterdata;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * 接送货地址信息
 */
public class CustShuttleaddress extends BaseEntity implements Serializable {
	private static final long serialVersionUID = -1544910985917059939L;

	/**
	 * 主键ID
	 */
	private BigDecimal fid;
	/**
	 * 创建时间
	 */
	private Date fcreatetime;
	/**
	 * 创建人
	 */
	private BigDecimal fcreateuserid;
	/**
     * 最后修改时间
	 */
	private Date flastupdatetime;
	/**
	 * 最后修改人
	 */
	private BigDecimal flastmodifyuserid;
	/**
	 * 详细地址
	 */
	private String faddress;
	/**
	 * 邮编
	 */
	private String fpostcode;
	/**
	 * 省份

	 */
	private String fprovince;
	/**
	 * 城市

	 */
	private String fcity;
	/**
	 * 区县

	 */
	private String farea;
	/**
	 * 地址类型

	 */
	private String faddresstype;
	/**
	 * 会员Id

	 */
	private BigDecimal fmemberid;
	
	/**
	 *  状态  正常：0；  审批中：1  ；无效 ：2；
	 */
	private BigDecimal fstatus;


	public BigDecimal getFid() {
		return fid;
	}
	
	/**
	 * 地址备注信息
	 */
	private String faddressRemark;

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DEVELOP.T_CUST_SHUTTLEADDRESS.FID
	 * @param fid  the value for DEVELOP.T_CUST_SHUTTLEADDRESS.FID
	 * @mbggenerated  Mon May 28 16:56:56 CST 2012
	 */
	public void setFid(BigDecimal fid) {
		this.fid = fid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DEVELOP.T_CUST_SHUTTLEADDRESS.FCREATETIME
	 * @return  the value of DEVELOP.T_CUST_SHUTTLEADDRESS.FCREATETIME
	 * @mbggenerated  Mon May 28 16:56:56 CST 2012
	 */
	public Date getFcreatetime() {
		return fcreatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DEVELOP.T_CUST_SHUTTLEADDRESS.FCREATETIME
	 * @param fcreatetime  the value for DEVELOP.T_CUST_SHUTTLEADDRESS.FCREATETIME
	 * @mbggenerated  Mon May 28 16:56:56 CST 2012
	 */
	public void setFcreatetime(Date fcreatetime) {
		this.fcreatetime = fcreatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DEVELOP.T_CUST_SHUTTLEADDRESS.FCREATEUSERID
	 * @return  the value of DEVELOP.T_CUST_SHUTTLEADDRESS.FCREATEUSERID
	 * @mbggenerated  Mon May 28 16:56:56 CST 2012
	 */
	public BigDecimal getFcreateuserid() {
		return fcreateuserid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DEVELOP.T_CUST_SHUTTLEADDRESS.FCREATEUSERID
	 * @param fcreateuserid  the value for DEVELOP.T_CUST_SHUTTLEADDRESS.FCREATEUSERID
	 * @mbggenerated  Mon May 28 16:56:56 CST 2012
	 */
	public void setFcreateuserid(BigDecimal fcreateuserid) {
		this.fcreateuserid = fcreateuserid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DEVELOP.T_CUST_SHUTTLEADDRESS.FLASTUPDATETIME
	 * @return  the value of DEVELOP.T_CUST_SHUTTLEADDRESS.FLASTUPDATETIME
	 * @mbggenerated  Mon May 28 16:56:56 CST 2012
	 */
	public Date getFlastupdatetime() {
		return flastupdatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DEVELOP.T_CUST_SHUTTLEADDRESS.FLASTUPDATETIME
	 * @param flastupdatetime  the value for DEVELOP.T_CUST_SHUTTLEADDRESS.FLASTUPDATETIME
	 * @mbggenerated  Mon May 28 16:56:56 CST 2012
	 */
	public void setFlastupdatetime(Date flastupdatetime) {
		this.flastupdatetime = flastupdatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DEVELOP.T_CUST_SHUTTLEADDRESS.FLASTMODIFYUSERID
	 * @return  the value of DEVELOP.T_CUST_SHUTTLEADDRESS.FLASTMODIFYUSERID
	 * @mbggenerated  Mon May 28 16:56:56 CST 2012
	 */
	public BigDecimal getFlastmodifyuserid() {
		return flastmodifyuserid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DEVELOP.T_CUST_SHUTTLEADDRESS.FLASTMODIFYUSERID
	 * @param flastmodifyuserid  the value for DEVELOP.T_CUST_SHUTTLEADDRESS.FLASTMODIFYUSERID
	 * @mbggenerated  Mon May 28 16:56:56 CST 2012
	 */
	public void setFlastmodifyuserid(BigDecimal flastmodifyuserid) {
		this.flastmodifyuserid = flastmodifyuserid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DEVELOP.T_CUST_SHUTTLEADDRESS.FADDRESS
	 * @return  the value of DEVELOP.T_CUST_SHUTTLEADDRESS.FADDRESS
	 * @mbggenerated  Mon May 28 16:56:56 CST 2012
	 */
	public String getFaddress() {
		return faddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DEVELOP.T_CUST_SHUTTLEADDRESS.FADDRESS
	 * @param faddress  the value for DEVELOP.T_CUST_SHUTTLEADDRESS.FADDRESS
	 * @mbggenerated  Mon May 28 16:56:56 CST 2012
	 */
	public void setFaddress(String faddress) {
		this.faddress = faddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DEVELOP.T_CUST_SHUTTLEADDRESS.FPOSTCODE
	 * @return  the value of DEVELOP.T_CUST_SHUTTLEADDRESS.FPOSTCODE
	 * @mbggenerated  Mon May 28 16:56:56 CST 2012
	 */
	public String getFpostcode() {
		return fpostcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DEVELOP.T_CUST_SHUTTLEADDRESS.FPOSTCODE
	 * @param fpostcode  the value for DEVELOP.T_CUST_SHUTTLEADDRESS.FPOSTCODE
	 * @mbggenerated  Mon May 28 16:56:56 CST 2012
	 */
	public void setFpostcode(String fpostcode) {
		this.fpostcode = fpostcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DEVELOP.T_CUST_SHUTTLEADDRESS.FPROVINCE
	 * @return  the value of DEVELOP.T_CUST_SHUTTLEADDRESS.FPROVINCE
	 * @mbggenerated  Mon May 28 16:56:56 CST 2012
	 */
	public String getFprovince() {
		return fprovince;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DEVELOP.T_CUST_SHUTTLEADDRESS.FPROVINCE
	 * @param fprovince  the value for DEVELOP.T_CUST_SHUTTLEADDRESS.FPROVINCE
	 * @mbggenerated  Mon May 28 16:56:56 CST 2012
	 */
	public void setFprovince(String fprovince) {
		this.fprovince = fprovince;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DEVELOP.T_CUST_SHUTTLEADDRESS.FCITY
	 * @return  the value of DEVELOP.T_CUST_SHUTTLEADDRESS.FCITY
	 * @mbggenerated  Mon May 28 16:56:56 CST 2012
	 */
	public String getFcity() {
		return fcity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DEVELOP.T_CUST_SHUTTLEADDRESS.FCITY
	 * @param fcity  the value for DEVELOP.T_CUST_SHUTTLEADDRESS.FCITY
	 * @mbggenerated  Mon May 28 16:56:56 CST 2012
	 */
	public void setFcity(String fcity) {
		this.fcity = fcity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DEVELOP.T_CUST_SHUTTLEADDRESS.FAREA
	 * @return  the value of DEVELOP.T_CUST_SHUTTLEADDRESS.FAREA
	 * @mbggenerated  Mon May 28 16:56:56 CST 2012
	 */
	public String getFarea() {
		return farea;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DEVELOP.T_CUST_SHUTTLEADDRESS.FAREA
	 * @param farea  the value for DEVELOP.T_CUST_SHUTTLEADDRESS.FAREA
	 * @mbggenerated  Mon May 28 16:56:56 CST 2012
	 */
	public void setFarea(String farea) {
		this.farea = farea;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DEVELOP.T_CUST_SHUTTLEADDRESS.FADDRESSTYPE
	 * @return  the value of DEVELOP.T_CUST_SHUTTLEADDRESS.FADDRESSTYPE
	 * @mbggenerated  Mon May 28 16:56:56 CST 2012
	 */
	public String getFaddresstype() {
		return faddresstype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DEVELOP.T_CUST_SHUTTLEADDRESS.FADDRESSTYPE
	 * @param faddresstype  the value for DEVELOP.T_CUST_SHUTTLEADDRESS.FADDRESSTYPE
	 * @mbggenerated  Mon May 28 16:56:56 CST 2012
	 */
	public void setFaddresstype(String faddresstype) {
		this.faddresstype = faddresstype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DEVELOP.T_CUST_SHUTTLEADDRESS.FMEMBERID
	 * @return  the value of DEVELOP.T_CUST_SHUTTLEADDRESS.FMEMBERID
	 * @mbggenerated  Mon May 28 16:56:56 CST 2012
	 */
	public BigDecimal getFmemberid() {
		return fmemberid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DEVELOP.T_CUST_SHUTTLEADDRESS.FMEMBERID
	 * @param fmemberid  the value for DEVELOP.T_CUST_SHUTTLEADDRESS.FMEMBERID
	 * @mbggenerated  Mon May 28 16:56:56 CST 2012
	 */
	public void setFmemberid(BigDecimal fmemberid) {
		this.fmemberid = fmemberid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DEVELOP.T_CUST_SHUTTLEADDRESS.FSTATUS
	 * @return  the value of DEVELOP.T_CUST_SHUTTLEADDRESS.FSTATUS
	 * @mbggenerated  Mon May 28 16:56:56 CST 2012
	 */
	public BigDecimal getFstatus() {
		return fstatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DEVELOP.T_CUST_SHUTTLEADDRESS.FSTATUS
	 * @param fstatus  the value for DEVELOP.T_CUST_SHUTTLEADDRESS.FSTATUS
	 * @mbggenerated  Mon May 28 16:56:56 CST 2012
	 */
	public void setFstatus(BigDecimal fstatus) {
		this.fstatus = fstatus;
	}

	public String getFaddressRemark() {
		return faddressRemark;
	}

	public void setFaddressRemark(String faddressRemark) {
		this.faddressRemark = faddressRemark;
	}

	@Override
	public String toString() {
		return "CustShuttleaddress [fid=" + fid + ", fcreatetime=" + fcreatetime + ", fcreateuserid=" + fcreateuserid
				+ ", flastupdatetime=" + flastupdatetime + ", flastmodifyuserid=" + flastmodifyuserid + ", faddress="
				+ faddress + ", fpostcode=" + fpostcode + ", fprovince=" + fprovince + ", fcity=" + fcity + ", farea="
				+ farea + ", faddresstype=" + faddresstype + ", fmemberid=" + fmemberid + ", fstatus=" + fstatus
				+ ", faddressRemark=" + faddressRemark + "]";
	}
	
	
}