package com.deppon.foss.dubbo.crm.api.define.masterdata;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * 合同信息
 *
 */
public class CustContract extends BaseEntity implements Serializable {
    /**
	 * 
	 */
	private static final long serialVersionUID = -6027375400199829022L;

	
    /**
     * 主键ID
     */
    private BigDecimal fid;

    /**
     * 创建时间
     */
    private Date fcreatetime;

    /**
     * 创建人id
     */
    private BigDecimal fcreateuserid;

    /**
     * 最后更新时间
     */
    private Date flastupdatetime;

    /**
     * 最后修改人id
     */
    private BigDecimal flastmodifyuserid;

    /**
     * 付款方式
     */
    private String fpayway;

    /**申请欠款额度
     */
    private BigDecimal farrearamount;

    /**
     * 协议联系人姓名
     */
    private String flinkmanname;

    /**
     * 联系人固定电话
     */
    private String flinkmanphone;

    /**
     * 联系人手机
     */
    private String flinkmanmobile;

    /**
     * 联系人详细地址
     */
    private String flinkmanaddress;

    /**
     * 合同起始日期
     */
    private Date fcontractbegindate;

    /**
     * 合同到期日期
     */
    private Date fcontractenddate;

    /**
     * 申请事由
     */
    private String fapplication;

    /**
     * 客户ID
     */
    private BigDecimal fcustid;

    /**
     * 部门ID
     */
    private BigDecimal fdeptid;

    /**
     * 是否折扣
     */
    private String fiddiscount;

    /**
     * 合同主体
     */
    private String fcontractsubject;

    /**
     * 注册资金
     */
    private String fregicapital;

    /**
     * 原合同编号
     */
    private String fbeforecontractnum;

    /**
     * 合同编号
     */
    private String fcontractnum;

    /**
     * 走货名称
     */
    private String fgoodsname;

    /**
     * 客户全称
     */
    private String fcustcompany;

    /**
     * 协议联系人id
     */
    private BigDecimal fcontactid;

    /**
     * 优惠类型
     */
    private String fpreferentialtype;

    /**
     * 对账日期
     */
    private BigDecimal frecondate;

    /**
     * 开发票日期
     */
    private BigDecimal finvoicdate;

    /**
     * 结款日期
     */
    private BigDecimal fresultdate;

    /**
     * 合同状态
	 */
    private String fcontractstatus;
  /**
     * 异地调货标志
	 */
    private boolean asyntakegoodscode;
  /**
     * 催款部门
	 */
    private String hastenfunddeptcode;
    
	/**
	 *  会员所属部门的标杆编码
	 */
	private String fdeptidStandardcode;
	
	/**
	 *合同月结天数
	*/
	private int debtDays;
	
	/**
	 *零担价格版本时间
	*/
	 private Date priceVersionDate;
	
	
	/**
	 * 快递价格版本时间
	 */
	 private Date exPriceVersionDate;
	/**
	 * 快递优惠类型
	 */
	 private String exPreferentialType;
	 
	 /**
	  * 快递结款方式
	  */
	 private String exPayWay;
	 
	 /**
	  * 是否单独报价
	  */
	 private boolean fIsSeparateQuote;
	 /**
	     * FOSS-232608
	     * 是否电商尊享
	     * 2015-07-08 吴苏华
	     */
	 private boolean ifElecEnjoy;


	public boolean isIfElecEnjoy() {
		return ifElecEnjoy;
	}

	public void setIfElecEnjoy(boolean ifElecEnjoy) {
		this.ifElecEnjoy = ifElecEnjoy;
	}

	public int getDebtDays(){
		return debtDays;
	}
	
	public void setDebtDays(int debtDays){
		this.debtDays=debtDays;
	}

              public String getFdeptidStandardcode() {
		return fdeptidStandardcode;
	}

	public void setFdeptidStandardcode(String fdeptidStandardcode) {
		this.fdeptidStandardcode = fdeptidStandardcode;
	}

	public boolean getAsyntakegoodscode(){
		return this.asyntakegoodscode;
	}

	public void setAsyntakegoodscode(boolean asyntakegoodscode){
		this.asyntakegoodscode=asyntakegoodscode;
	} 

	public String getHastenfunddeptcode(){
		return this.hastenfunddeptcode;
	}

	public void setHastenfunddeptcode(String hastenfunddeptcode){
		this.hastenfunddeptcode=hastenfunddeptcode;	
	}
	
     /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVELOP.T_CUST_CONTRACT.FID
     *
     * @return the value of DEVELOP.T_CUST_CONTRACT.FID
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    public BigDecimal getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVELOP.T_CUST_CONTRACT.FID
     *
     * @param fid the value for DEVELOP.T_CUST_CONTRACT.FID
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    public void setFid(BigDecimal fid) {
        this.fid = fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVELOP.T_CUST_CONTRACT.FCREATETIME
     *
     * @return the value of DEVELOP.T_CUST_CONTRACT.FCREATETIME
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    public Date getFcreatetime() {
        return fcreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVELOP.T_CUST_CONTRACT.FCREATETIME
     *
     * @param fcreatetime the value for DEVELOP.T_CUST_CONTRACT.FCREATETIME
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    public void setFcreatetime(Date fcreatetime) {
        this.fcreatetime = fcreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVELOP.T_CUST_CONTRACT.FCREATEUSERID
     *
     * @return the value of DEVELOP.T_CUST_CONTRACT.FCREATEUSERID
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    public BigDecimal getFcreateuserid() {
        return fcreateuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVELOP.T_CUST_CONTRACT.FCREATEUSERID
     *
     * @param fcreateuserid the value for DEVELOP.T_CUST_CONTRACT.FCREATEUSERID
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    public void setFcreateuserid(BigDecimal fcreateuserid) {
        this.fcreateuserid = fcreateuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVELOP.T_CUST_CONTRACT.FLASTUPDATETIME
     *
     * @return the value of DEVELOP.T_CUST_CONTRACT.FLASTUPDATETIME
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    public Date getFlastupdatetime() {
        return flastupdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVELOP.T_CUST_CONTRACT.FLASTUPDATETIME
     *
     * @param flastupdatetime the value for DEVELOP.T_CUST_CONTRACT.FLASTUPDATETIME
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    public void setFlastupdatetime(Date flastupdatetime) {
        this.flastupdatetime = flastupdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVELOP.T_CUST_CONTRACT.FLASTMODIFYUSERID
     *
     * @return the value of DEVELOP.T_CUST_CONTRACT.FLASTMODIFYUSERID
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    public BigDecimal getFlastmodifyuserid() {
        return flastmodifyuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVELOP.T_CUST_CONTRACT.FLASTMODIFYUSERID
     *
     * @param flastmodifyuserid the value for DEVELOP.T_CUST_CONTRACT.FLASTMODIFYUSERID
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    public void setFlastmodifyuserid(BigDecimal flastmodifyuserid) {
        this.flastmodifyuserid = flastmodifyuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVELOP.T_CUST_CONTRACT.FPAYWAY
     *
     * @return the value of DEVELOP.T_CUST_CONTRACT.FPAYWAY
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    public String getFpayway() {
        return fpayway;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVELOP.T_CUST_CONTRACT.FPAYWAY
     *
     * @param fpayway the value for DEVELOP.T_CUST_CONTRACT.FPAYWAY
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    public void setFpayway(String fpayway) {
        this.fpayway = fpayway;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVELOP.T_CUST_CONTRACT.FARREARAMOUNT
     *
     * @return the value of DEVELOP.T_CUST_CONTRACT.FARREARAMOUNT
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    public BigDecimal getFarrearamount() {
        return farrearamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVELOP.T_CUST_CONTRACT.FARREARAMOUNT
     *
     * @param farrearamount the value for DEVELOP.T_CUST_CONTRACT.FARREARAMOUNT
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    public void setFarrearamount(BigDecimal farrearamount) {
        this.farrearamount = farrearamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVELOP.T_CUST_CONTRACT.FLINKMANNAME
     *
     * @return the value of DEVELOP.T_CUST_CONTRACT.FLINKMANNAME
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    public String getFlinkmanname() {
        return flinkmanname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVELOP.T_CUST_CONTRACT.FLINKMANNAME
     *
     * @param flinkmanname the value for DEVELOP.T_CUST_CONTRACT.FLINKMANNAME
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    public void setFlinkmanname(String flinkmanname) {
        this.flinkmanname = flinkmanname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVELOP.T_CUST_CONTRACT.FLINKMANPHONE
     *
     * @return the value of DEVELOP.T_CUST_CONTRACT.FLINKMANPHONE
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    public String getFlinkmanphone() {
        return flinkmanphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVELOP.T_CUST_CONTRACT.FLINKMANPHONE
     *
     * @param flinkmanphone the value for DEVELOP.T_CUST_CONTRACT.FLINKMANPHONE
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    public void setFlinkmanphone(String flinkmanphone) {
        this.flinkmanphone = flinkmanphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVELOP.T_CUST_CONTRACT.FLINKMANMOBILE
     *
     * @return the value of DEVELOP.T_CUST_CONTRACT.FLINKMANMOBILE
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    public String getFlinkmanmobile() {
        return flinkmanmobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVELOP.T_CUST_CONTRACT.FLINKMANMOBILE
     *
     * @param flinkmanmobile the value for DEVELOP.T_CUST_CONTRACT.FLINKMANMOBILE
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    public void setFlinkmanmobile(String flinkmanmobile) {
        this.flinkmanmobile = flinkmanmobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVELOP.T_CUST_CONTRACT.FLINKMANADDRESS
     *
     * @return the value of DEVELOP.T_CUST_CONTRACT.FLINKMANADDRESS
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    public String getFlinkmanaddress() {
        return flinkmanaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVELOP.T_CUST_CONTRACT.FLINKMANADDRESS
     *
     * @param flinkmanaddress the value for DEVELOP.T_CUST_CONTRACT.FLINKMANADDRESS
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    public void setFlinkmanaddress(String flinkmanaddress) {
        this.flinkmanaddress = flinkmanaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVELOP.T_CUST_CONTRACT.FCONTRACTBEGINDATE
     *
     * @return the value of DEVELOP.T_CUST_CONTRACT.FCONTRACTBEGINDATE
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    public Date getFcontractbegindate() {
        return fcontractbegindate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVELOP.T_CUST_CONTRACT.FCONTRACTBEGINDATE
     *
     * @param fcontractbegindate the value for DEVELOP.T_CUST_CONTRACT.FCONTRACTBEGINDATE
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    public void setFcontractbegindate(Date fcontractbegindate) {
        this.fcontractbegindate = fcontractbegindate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVELOP.T_CUST_CONTRACT.FCONTRACTENDDATE
     *
     * @return the value of DEVELOP.T_CUST_CONTRACT.FCONTRACTENDDATE
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    public Date getFcontractenddate() {
        return fcontractenddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVELOP.T_CUST_CONTRACT.FCONTRACTENDDATE
     *
     * @param fcontractenddate the value for DEVELOP.T_CUST_CONTRACT.FCONTRACTENDDATE
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    public void setFcontractenddate(Date fcontractenddate) {
        this.fcontractenddate = fcontractenddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVELOP.T_CUST_CONTRACT.FAPPLICATION
     *
     * @return the value of DEVELOP.T_CUST_CONTRACT.FAPPLICATION
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    public String getFapplication() {
        return fapplication;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVELOP.T_CUST_CONTRACT.FAPPLICATION
     *
     * @param fapplication the value for DEVELOP.T_CUST_CONTRACT.FAPPLICATION
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    public void setFapplication(String fapplication) {
        this.fapplication = fapplication;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVELOP.T_CUST_CONTRACT.FCUSTID
     *
     * @return the value of DEVELOP.T_CUST_CONTRACT.FCUSTID
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    public BigDecimal getFcustid() {
        return fcustid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVELOP.T_CUST_CONTRACT.FCUSTID
     *
     * @param fcustid the value for DEVELOP.T_CUST_CONTRACT.FCUSTID
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    public void setFcustid(BigDecimal fcustid) {
        this.fcustid = fcustid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVELOP.T_CUST_CONTRACT.FDEPTID
     *
     * @return the value of DEVELOP.T_CUST_CONTRACT.FDEPTID
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    public BigDecimal getFdeptid() {
        return fdeptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVELOP.T_CUST_CONTRACT.FDEPTID
     *
     * @param fdeptid the value for DEVELOP.T_CUST_CONTRACT.FDEPTID
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    public void setFdeptid(BigDecimal fdeptid) {
        this.fdeptid = fdeptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVELOP.T_CUST_CONTRACT.FIDDISCOUNT
     *
     * @return the value of DEVELOP.T_CUST_CONTRACT.FIDDISCOUNT
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    public String getFiddiscount() {
        return fiddiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVELOP.T_CUST_CONTRACT.FIDDISCOUNT
     *
     * @param fiddiscount the value for DEVELOP.T_CUST_CONTRACT.FIDDISCOUNT
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    public void setFiddiscount(String fiddiscount) {
        this.fiddiscount = fiddiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVELOP.T_CUST_CONTRACT.FCONTRACTSUBJECT
     *
     * @return the value of DEVELOP.T_CUST_CONTRACT.FCONTRACTSUBJECT
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    public String getFcontractsubject() {
        return fcontractsubject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVELOP.T_CUST_CONTRACT.FCONTRACTSUBJECT
     *
     * @param fcontractsubject the value for DEVELOP.T_CUST_CONTRACT.FCONTRACTSUBJECT
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    public void setFcontractsubject(String fcontractsubject) {
        this.fcontractsubject = fcontractsubject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVELOP.T_CUST_CONTRACT.FREGICAPITAL
     *
     * @return the value of DEVELOP.T_CUST_CONTRACT.FREGICAPITAL
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    public String getFregicapital() {
        return fregicapital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVELOP.T_CUST_CONTRACT.FREGICAPITAL
     *
     * @param fregicapital the value for DEVELOP.T_CUST_CONTRACT.FREGICAPITAL
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    public void setFregicapital(String fregicapital) {
        this.fregicapital = fregicapital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVELOP.T_CUST_CONTRACT.FBEFORECONTRACTNUM
     *
     * @return the value of DEVELOP.T_CUST_CONTRACT.FBEFORECONTRACTNUM
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    public String getFbeforecontractnum() {
        return fbeforecontractnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVELOP.T_CUST_CONTRACT.FBEFORECONTRACTNUM
     *
     * @param fbeforecontractnum the value for DEVELOP.T_CUST_CONTRACT.FBEFORECONTRACTNUM
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    public void setFbeforecontractnum(String fbeforecontractnum) {
        this.fbeforecontractnum = fbeforecontractnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVELOP.T_CUST_CONTRACT.FCONTRACTNUM
     *
     * @return the value of DEVELOP.T_CUST_CONTRACT.FCONTRACTNUM
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    public String getFcontractnum() {
        return fcontractnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVELOP.T_CUST_CONTRACT.FCONTRACTNUM
     *
     * @param fcontractnum the value for DEVELOP.T_CUST_CONTRACT.FCONTRACTNUM
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    public void setFcontractnum(String fcontractnum) {
        this.fcontractnum = fcontractnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVELOP.T_CUST_CONTRACT.FGOODSNAME
     *
     * @return the value of DEVELOP.T_CUST_CONTRACT.FGOODSNAME
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    public String getFgoodsname() {
        return fgoodsname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVELOP.T_CUST_CONTRACT.FGOODSNAME
     *
     * @param fgoodsname the value for DEVELOP.T_CUST_CONTRACT.FGOODSNAME
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    public void setFgoodsname(String fgoodsname) {
        this.fgoodsname = fgoodsname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVELOP.T_CUST_CONTRACT.FCUSTCOMPANY
     *
     * @return the value of DEVELOP.T_CUST_CONTRACT.FCUSTCOMPANY
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    public String getFcustcompany() {
        return fcustcompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVELOP.T_CUST_CONTRACT.FCUSTCOMPANY
     *
     * @param fcustcompany the value for DEVELOP.T_CUST_CONTRACT.FCUSTCOMPANY
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    public void setFcustcompany(String fcustcompany) {
        this.fcustcompany = fcustcompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVELOP.T_CUST_CONTRACT.FCONTACTID
     *
     * @return the value of DEVELOP.T_CUST_CONTRACT.FCONTACTID
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    public BigDecimal getFcontactid() {
        return fcontactid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVELOP.T_CUST_CONTRACT.FCONTACTID
     *
     * @param fcontactid the value for DEVELOP.T_CUST_CONTRACT.FCONTACTID
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    public void setFcontactid(BigDecimal fcontactid) {
        this.fcontactid = fcontactid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVELOP.T_CUST_CONTRACT.FPREFERENTIALTYPE
     *
     * @return the value of DEVELOP.T_CUST_CONTRACT.FPREFERENTIALTYPE
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    public String getFpreferentialtype() {
        return fpreferentialtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVELOP.T_CUST_CONTRACT.FPREFERENTIALTYPE
     *
     * @param fpreferentialtype the value for DEVELOP.T_CUST_CONTRACT.FPREFERENTIALTYPE
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    public void setFpreferentialtype(String fpreferentialtype) {
        this.fpreferentialtype = fpreferentialtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVELOP.T_CUST_CONTRACT.FRECONDATE
     *
     * @return the value of DEVELOP.T_CUST_CONTRACT.FRECONDATE
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    public BigDecimal getFrecondate() {
        return frecondate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVELOP.T_CUST_CONTRACT.FRECONDATE
     *
     * @param frecondate the value for DEVELOP.T_CUST_CONTRACT.FRECONDATE
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    public void setFrecondate(BigDecimal frecondate) {
        this.frecondate = frecondate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVELOP.T_CUST_CONTRACT.FINVOICDATE
     *
     * @return the value of DEVELOP.T_CUST_CONTRACT.FINVOICDATE
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    public BigDecimal getFinvoicdate() {
        return finvoicdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVELOP.T_CUST_CONTRACT.FINVOICDATE
     *
     * @param finvoicdate the value for DEVELOP.T_CUST_CONTRACT.FINVOICDATE
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    public void setFinvoicdate(BigDecimal finvoicdate) {
        this.finvoicdate = finvoicdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVELOP.T_CUST_CONTRACT.FRESULTDATE
     *
     * @return the value of DEVELOP.T_CUST_CONTRACT.FRESULTDATE
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    public BigDecimal getFresultdate() {
        return fresultdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVELOP.T_CUST_CONTRACT.FRESULTDATE
     *
     * @param fresultdate the value for DEVELOP.T_CUST_CONTRACT.FRESULTDATE
     *
     * @mbggenerated Mon May 28 16:56:56 CST 2012
     */
    public void setFresultdate(BigDecimal fresultdate) {
        this.fresultdate = fresultdate;
    }

	public String getFcontractstatus() {
		return fcontractstatus;
	}

	public void setFcontractstatus(String fcontractstatus) {
		this.fcontractstatus = fcontractstatus;
	}
	
	/**
	 * 获取零担价格版本时间.
	 * @return
	 */
	public Date getPriceVersionDate() {
		return priceVersionDate;
	}
	
	/**
	 * 设置零担价格版本时间.
	 * @param priceVersionDate
	 */
	public void setPriceVersionDate(Date priceVersionDate) {
		this.priceVersionDate = priceVersionDate;
	}
	
	public String getExPreferentialType() {
		return exPreferentialType;
	}

	public void setExPreferentialType(String exPreferentialType) {
		this.exPreferentialType = exPreferentialType;
	}

	public String getExPayWay() {
		return exPayWay;
	}

	public void setExPayWay(String exPayWay) {
		this.exPayWay = exPayWay;
	}

	public Date getExPriceVersionDate() {
		return exPriceVersionDate;
	}

	public void setExPriceVersionDate(Date exPriceVersionDate) {
		this.exPriceVersionDate = exPriceVersionDate;
	}

	public boolean isfIsSeparateQuote() {
		return fIsSeparateQuote;
	}

	public void setfIsSeparateQuote(boolean fIsSeparateQuote) {
		this.fIsSeparateQuote = fIsSeparateQuote;
	}

	@Override
	public String toString() {
		return "CustContract [fid=" + fid + ", fcreatetime=" + fcreatetime + ", fcreateuserid=" + fcreateuserid
				+ ", flastupdatetime=" + flastupdatetime + ", flastmodifyuserid=" + flastmodifyuserid + ", fpayway="
				+ fpayway + ", farrearamount=" + farrearamount + ", flinkmanname=" + flinkmanname + ", flinkmanphone="
				+ flinkmanphone + ", flinkmanmobile=" + flinkmanmobile + ", flinkmanaddress=" + flinkmanaddress
				+ ", fcontractbegindate=" + fcontractbegindate + ", fcontractenddate=" + fcontractenddate
				+ ", fapplication=" + fapplication + ", fcustid=" + fcustid + ", fdeptid=" + fdeptid + ", fiddiscount="
				+ fiddiscount + ", fcontractsubject=" + fcontractsubject + ", fregicapital=" + fregicapital
				+ ", fbeforecontractnum=" + fbeforecontractnum + ", fcontractnum=" + fcontractnum + ", fgoodsname="
				+ fgoodsname + ", fcustcompany=" + fcustcompany + ", fcontactid=" + fcontactid + ", fpreferentialtype="
				+ fpreferentialtype + ", frecondate=" + frecondate + ", finvoicdate=" + finvoicdate + ", fresultdate="
				+ fresultdate + ", fcontractstatus=" + fcontractstatus + ", asyntakegoodscode=" + asyntakegoodscode
				+ ", hastenfunddeptcode=" + hastenfunddeptcode + ", fdeptidStandardcode=" + fdeptidStandardcode
				+ ", debtDays=" + debtDays + ", priceVersionDate=" + priceVersionDate + ", exPriceVersionDate="
				+ exPriceVersionDate + ", exPreferentialType=" + exPreferentialType + ", exPayWay=" + exPayWay
				+ ", fIsSeparateQuote=" + fIsSeparateQuote + ", ifElecEnjoy=" + ifElecEnjoy + "]";
	}

	
	
}