package com.deppon.foss.module.transfer.platform.api.shared.domain;

import java.math.BigDecimal;
import java.util.Date;

import com.deppon.foss.framework.entity.BaseEntity;

public class CarEfficiencyEntity extends BaseEntity {
    
	/**
	* @fields serialVersionUID
	* @author 14022-foss-songjie
	* @update 2014年5月5日 上午10:22:58
	* @version V1.0
	*/
	
	private static final long serialVersionUID = 1L;

	/**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T_OPT_CAR_TEMP.ACTUAL_DEPART_TIME
     *
     * @ibatorgenerated Mon May 05 10:21:53 CST 2014
     */
    private String actualDepartTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T_OPT_CAR_TEMP.BILL_NO
     *
     * @ibatorgenerated Mon May 05 10:21:53 CST 2014
     */
    private String billNo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T_OPT_CAR_TEMP.VEHICLE_NO
     *
     * @ibatorgenerated Mon May 05 10:21:53 CST 2014
     */
    private String vehicleNo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T_OPT_CAR_TEMP.ORG_NAME
     *
     * @ibatorgenerated Mon May 05 10:21:53 CST 2014
     */
    private String orgName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T_OPT_CAR_TEMP.WEIGHT_TOTAL
     *
     * @ibatorgenerated Mon May 05 10:21:53 CST 2014
     */
    private BigDecimal weightTotal;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T_OPT_CAR_TEMP.START_TIME
     *
     * @ibatorgenerated Mon May 05 10:21:53 CST 2014
     */
    private Date startTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T_OPT_CAR_TEMP.END_TIME
     *
     * @ibatorgenerated Mon May 05 10:21:53 CST 2014
     */
    private Date endTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T_OPT_CAR_TEMP.TASK_IDS
     *
     * @ibatorgenerated Mon May 05 10:21:53 CST 2014
     */
    private String taskIds;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T_OPT_CAR_TEMP.TYPE_LOAD
     *
     * @ibatorgenerated Mon May 05 10:21:53 CST 2014
     */
    private String typeLoad;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T_OPT_CAR_TEMP.TIME_SECTION
     *
     * @ibatorgenerated Mon May 05 10:21:53 CST 2014
     */
    private String timeSection;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T_OPT_CAR_TEMP.EFFICIENCY
     *
     * @ibatorgenerated Mon May 05 10:21:53 CST 2014
     */
    private String efficiency;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T_OPT_CAR_TEMP.FLAG_PASSING
     *
     * @ibatorgenerated Mon May 05 10:21:53 CST 2014
     */
    private String flagPassing;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T_OPT_CAR_TEMP.ORG_CODE
     *
     * @ibatorgenerated Mon May 05 10:21:53 CST 2014
     */
    private String orgCode;
    
    
    
    /**
     * 理货员Code
    * @fields loaderCode
    * @author 14022-foss-songjie
    * @update 2014年5月5日 下午2:36:33
    * @version V1.0
    */
    private String loaderCode;
    
    /**
     *  理货员 Name
    * @fields loaderName
    * @author 14022-foss-songjie
    * @update 2014年5月5日 下午2:36:36
    * @version V1.0
    */
    private String loaderName;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T_OPT_CAR_TEMP.ACTUAL_DEPART_TIME
     *
     * @return the value of T_OPT_CAR_TEMP.ACTUAL_DEPART_TIME
     *
     * @ibatorgenerated Mon May 05 10:21:53 CST 2014
     */
    public String getActualDepartTime() {
        return actualDepartTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T_OPT_CAR_TEMP.ACTUAL_DEPART_TIME
     *
     * @param actualDepartTime the value for T_OPT_CAR_TEMP.ACTUAL_DEPART_TIME
     *
     * @ibatorgenerated Mon May 05 10:21:53 CST 2014
     */
    public void setActualDepartTime(String actualDepartTime) {
        this.actualDepartTime = actualDepartTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T_OPT_CAR_TEMP.BILL_NO
     *
     * @return the value of T_OPT_CAR_TEMP.BILL_NO
     *
     * @ibatorgenerated Mon May 05 10:21:53 CST 2014
     */
    public String getBillNo() {
        return billNo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T_OPT_CAR_TEMP.BILL_NO
     *
     * @param billNo the value for T_OPT_CAR_TEMP.BILL_NO
     *
     * @ibatorgenerated Mon May 05 10:21:53 CST 2014
     */
    public void setBillNo(String billNo) {
        this.billNo = billNo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T_OPT_CAR_TEMP.VEHICLE_NO
     *
     * @return the value of T_OPT_CAR_TEMP.VEHICLE_NO
     *
     * @ibatorgenerated Mon May 05 10:21:53 CST 2014
     */
    public String getVehicleNo() {
        return vehicleNo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T_OPT_CAR_TEMP.VEHICLE_NO
     *
     * @param vehicleNo the value for T_OPT_CAR_TEMP.VEHICLE_NO
     *
     * @ibatorgenerated Mon May 05 10:21:53 CST 2014
     */
    public void setVehicleNo(String vehicleNo) {
        this.vehicleNo = vehicleNo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T_OPT_CAR_TEMP.ORG_NAME
     *
     * @return the value of T_OPT_CAR_TEMP.ORG_NAME
     *
     * @ibatorgenerated Mon May 05 10:21:53 CST 2014
     */
    public String getOrgName() {
        return orgName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T_OPT_CAR_TEMP.ORG_NAME
     *
     * @param orgName the value for T_OPT_CAR_TEMP.ORG_NAME
     *
     * @ibatorgenerated Mon May 05 10:21:53 CST 2014
     */
    public void setOrgName(String orgName) {
        this.orgName = orgName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T_OPT_CAR_TEMP.WEIGHT_TOTAL
     *
     * @return the value of T_OPT_CAR_TEMP.WEIGHT_TOTAL
     *
     * @ibatorgenerated Mon May 05 10:21:53 CST 2014
     */
    public BigDecimal getWeightTotal() {
        return weightTotal;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T_OPT_CAR_TEMP.WEIGHT_TOTAL
     *
     * @param weightTotal the value for T_OPT_CAR_TEMP.WEIGHT_TOTAL
     *
     * @ibatorgenerated Mon May 05 10:21:53 CST 2014
     */
    public void setWeightTotal(BigDecimal weightTotal) {
        this.weightTotal = weightTotal;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T_OPT_CAR_TEMP.START_TIME
     *
     * @return the value of T_OPT_CAR_TEMP.START_TIME
     *
     * @ibatorgenerated Mon May 05 10:21:53 CST 2014
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T_OPT_CAR_TEMP.START_TIME
     *
     * @param startTime the value for T_OPT_CAR_TEMP.START_TIME
     *
     * @ibatorgenerated Mon May 05 10:21:53 CST 2014
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T_OPT_CAR_TEMP.END_TIME
     *
     * @return the value of T_OPT_CAR_TEMP.END_TIME
     *
     * @ibatorgenerated Mon May 05 10:21:53 CST 2014
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T_OPT_CAR_TEMP.END_TIME
     *
     * @param endTime the value for T_OPT_CAR_TEMP.END_TIME
     *
     * @ibatorgenerated Mon May 05 10:21:53 CST 2014
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T_OPT_CAR_TEMP.TASK_IDS
     *
     * @return the value of T_OPT_CAR_TEMP.TASK_IDS
     *
     * @ibatorgenerated Mon May 05 10:21:53 CST 2014
     */
    public String getTaskIds() {
        return taskIds;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T_OPT_CAR_TEMP.TASK_IDS
     *
     * @param taskIds the value for T_OPT_CAR_TEMP.TASK_IDS
     *
     * @ibatorgenerated Mon May 05 10:21:53 CST 2014
     */
    public void setTaskIds(String taskIds) {
        this.taskIds = taskIds;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T_OPT_CAR_TEMP.TYPE_LOAD
     *
     * @return the value of T_OPT_CAR_TEMP.TYPE_LOAD
     *
     * @ibatorgenerated Mon May 05 10:21:53 CST 2014
     */
    public String getTypeLoad() {
        return typeLoad;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T_OPT_CAR_TEMP.TYPE_LOAD
     *
     * @param typeLoad the value for T_OPT_CAR_TEMP.TYPE_LOAD
     *
     * @ibatorgenerated Mon May 05 10:21:53 CST 2014
     */
    public void setTypeLoad(String typeLoad) {
        this.typeLoad = typeLoad;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T_OPT_CAR_TEMP.TIME_SECTION
     *
     * @return the value of T_OPT_CAR_TEMP.TIME_SECTION
     *
     * @ibatorgenerated Mon May 05 10:21:53 CST 2014
     */
    public String getTimeSection() {
        return timeSection;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T_OPT_CAR_TEMP.TIME_SECTION
     *
     * @param timeSection the value for T_OPT_CAR_TEMP.TIME_SECTION
     *
     * @ibatorgenerated Mon May 05 10:21:53 CST 2014
     */
    public void setTimeSection(String timeSection) {
        this.timeSection = timeSection;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T_OPT_CAR_TEMP.EFFICIENCY
     *
     * @return the value of T_OPT_CAR_TEMP.EFFICIENCY
     *
     * @ibatorgenerated Mon May 05 10:21:53 CST 2014
     */
    public String getEfficiency() {
        return efficiency;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T_OPT_CAR_TEMP.EFFICIENCY
     *
     * @param efficiency the value for T_OPT_CAR_TEMP.EFFICIENCY
     *
     * @ibatorgenerated Mon May 05 10:21:53 CST 2014
     */
    public void setEfficiency(String efficiency) {
        this.efficiency = efficiency;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T_OPT_CAR_TEMP.FLAG_PASSING
     *
     * @return the value of T_OPT_CAR_TEMP.FLAG_PASSING
     *
     * @ibatorgenerated Mon May 05 10:21:53 CST 2014
     */
    public String getFlagPassing() {
        return flagPassing;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T_OPT_CAR_TEMP.FLAG_PASSING
     *
     * @param flagPassing the value for T_OPT_CAR_TEMP.FLAG_PASSING
     *
     * @ibatorgenerated Mon May 05 10:21:53 CST 2014
     */
    public void setFlagPassing(String flagPassing) {
        this.flagPassing = flagPassing;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T_OPT_CAR_TEMP.ORG_CODE
     *
     * @return the value of T_OPT_CAR_TEMP.ORG_CODE
     *
     * @ibatorgenerated Mon May 05 10:21:53 CST 2014
     */
    public String getOrgCode() {
        return orgCode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T_OPT_CAR_TEMP.ORG_CODE
     *
     * @param orgCode the value for T_OPT_CAR_TEMP.ORG_CODE
     *
     * @ibatorgenerated Mon May 05 10:21:53 CST 2014
     */
    public void setOrgCode(String orgCode) {
        this.orgCode = orgCode;
    }

	
	/**
	* @description  理货员Code
	* @return
	* @version 1.0
	* @author 14022-foss-songjie
	* @update 2014年5月5日 下午2:37:06
	*/
	public String getLoaderCode() {
		return loaderCode;
	}

	
	/**
	* @description  理货员Code
	* @param loaderCode
	* @version 1.0
	* @author 14022-foss-songjie
	* @update 2014年5月5日 下午2:37:14
	*/
	public void setLoaderCode(String loaderCode) {
		this.loaderCode = loaderCode;
	}

	
	/**
	* @description  理货员Name
	* @return
	* @version 1.0
	* @author 14022-foss-songjie
	* @update 2014年5月5日 下午2:37:20
	*/
	public String getLoaderName() {
		return loaderName;
	}

	
	/**
	* @description  理货员Name
	* @param loaderName
	* @version 1.0
	* @author 14022-foss-songjie
	* @update 2014年5月5日 下午2:37:28
	*/
	public void setLoaderName(String loaderName) {
		this.loaderName = loaderName;
	}
    
    
}