package com.deppon.foss.module.transfer.platform.api.shared.domain;

import java.math.BigDecimal;

import com.deppon.foss.framework.entity.BaseEntity;


/**
* @description  卸车进度里的 未卸车明细
* @version 1.0
* @author 14022-foss-songjie
* @update 2014年4月16日 下午2:28:50
*/
public class NoUnloadGoodsDetail extends BaseEntity{
    
	/**
	* @fields serialVersionUID
	* @author 14022-foss-songjie
	* @update 2014年4月16日 下午2:28:57
	* @version V1.0
	*/
	
	private static final long serialVersionUID = 1L;

	/**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T_OPT_NOUNLOAD_GOODS_DETAIL.ID
     *
     * @ibatorgenerated Wed Apr 16 14:27:54 CST 2014
     */
    private String id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T_OPT_NOUNLOAD_GOODS_DETAIL.WAYBILL_NO
     *
     * @ibatorgenerated Wed Apr 16 14:27:54 CST 2014
     */
    private String waybillNo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T_OPT_NOUNLOAD_GOODS_DETAIL.GOODS_QTY_TOTAL
     *
     * @ibatorgenerated Wed Apr 16 14:27:54 CST 2014
     */
    private BigDecimal goodsQtyTotal;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T_OPT_NOUNLOAD_GOODS_DETAIL.HANDOVER_GOODS_QTY
     *
     * @ibatorgenerated Wed Apr 16 14:27:54 CST 2014
     */
    private BigDecimal handoverGoodsQty;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T_OPT_NOUNLOAD_GOODS_DETAIL.NOUNLOAD_GOODS_QTY
     *
     * @ibatorgenerated Wed Apr 16 14:27:54 CST 2014
     */
    private BigDecimal nounloadGoodsQty;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T_OPT_NOUNLOAD_GOODS_DETAIL.GOODS_WEIGHT_TOTAL
     *
     * @ibatorgenerated Wed Apr 16 14:27:54 CST 2014
     */
    private BigDecimal goodsWeightTotal;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T_OPT_NOUNLOAD_GOODS_DETAIL.GOODS_VOLUME_TOTAL
     *
     * @ibatorgenerated Wed Apr 16 14:27:54 CST 2014
     */
    private BigDecimal goodsVolumeTotal;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T_OPT_NOUNLOAD_GOODS_DETAIL.NEXT_ORGNAME
     *
     * @ibatorgenerated Wed Apr 16 14:27:54 CST 2014
     */
    private String nextOrgname;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T_OPT_NOUNLOAD_GOODS_DETAIL.UNLOAD_ORG_CODE
     *
     * @ibatorgenerated Wed Apr 16 14:27:54 CST 2014
     */
    private String unloadOrgCode;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T_OPT_NOUNLOAD_GOODS_DETAIL.PRODUCT_CODE
     *
     * @ibatorgenerated Wed Apr 16 14:27:54 CST 2014
     */
    private String productCode;
    
    
    
    /**
    * @fields goodsWeightSum
    * @author 14022-foss-songjie
    * @update 2014年4月19日 下午2:02:08
    * @version V1.0
    */
    private BigDecimal goodsWeightSum;

    /**
    * @fields goodsVolumeSum
    * @author 14022-foss-songjie
    * @update 2014年4月19日 下午2:02:11
    * @version V1.0
    */
    private BigDecimal goodsVolumeSum;
    

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T_OPT_NOUNLOAD_GOODS_DETAIL.ID
     *
     * @return the value of T_OPT_NOUNLOAD_GOODS_DETAIL.ID
     *
     * @ibatorgenerated Wed Apr 16 14:27:54 CST 2014
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T_OPT_NOUNLOAD_GOODS_DETAIL.ID
     *
     * @param id the value for T_OPT_NOUNLOAD_GOODS_DETAIL.ID
     *
     * @ibatorgenerated Wed Apr 16 14:27:54 CST 2014
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T_OPT_NOUNLOAD_GOODS_DETAIL.WAYBILL_NO
     *
     * @return the value of T_OPT_NOUNLOAD_GOODS_DETAIL.WAYBILL_NO
     *
     * @ibatorgenerated Wed Apr 16 14:27:54 CST 2014
     */
    public String getWaybillNo() {
        return waybillNo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T_OPT_NOUNLOAD_GOODS_DETAIL.WAYBILL_NO
     *
     * @param waybillNo the value for T_OPT_NOUNLOAD_GOODS_DETAIL.WAYBILL_NO
     *
     * @ibatorgenerated Wed Apr 16 14:27:54 CST 2014
     */
    public void setWaybillNo(String waybillNo) {
        this.waybillNo = waybillNo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T_OPT_NOUNLOAD_GOODS_DETAIL.GOODS_QTY_TOTAL
     *
     * @return the value of T_OPT_NOUNLOAD_GOODS_DETAIL.GOODS_QTY_TOTAL
     *
     * @ibatorgenerated Wed Apr 16 14:27:54 CST 2014
     */
    public BigDecimal getGoodsQtyTotal() {
        return goodsQtyTotal;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T_OPT_NOUNLOAD_GOODS_DETAIL.GOODS_QTY_TOTAL
     *
     * @param goodsQtyTotal the value for T_OPT_NOUNLOAD_GOODS_DETAIL.GOODS_QTY_TOTAL
     *
     * @ibatorgenerated Wed Apr 16 14:27:54 CST 2014
     */
    public void setGoodsQtyTotal(BigDecimal goodsQtyTotal) {
        this.goodsQtyTotal = goodsQtyTotal;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T_OPT_NOUNLOAD_GOODS_DETAIL.HANDOVER_GOODS_QTY
     *
     * @return the value of T_OPT_NOUNLOAD_GOODS_DETAIL.HANDOVER_GOODS_QTY
     *
     * @ibatorgenerated Wed Apr 16 14:27:54 CST 2014
     */
    public BigDecimal getHandoverGoodsQty() {
        return handoverGoodsQty;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T_OPT_NOUNLOAD_GOODS_DETAIL.HANDOVER_GOODS_QTY
     *
     * @param handoverGoodsQty the value for T_OPT_NOUNLOAD_GOODS_DETAIL.HANDOVER_GOODS_QTY
     *
     * @ibatorgenerated Wed Apr 16 14:27:54 CST 2014
     */
    public void setHandoverGoodsQty(BigDecimal handoverGoodsQty) {
        this.handoverGoodsQty = handoverGoodsQty;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T_OPT_NOUNLOAD_GOODS_DETAIL.NOUNLOAD_GOODS_QTY
     *
     * @return the value of T_OPT_NOUNLOAD_GOODS_DETAIL.NOUNLOAD_GOODS_QTY
     *
     * @ibatorgenerated Wed Apr 16 14:27:54 CST 2014
     */
    public BigDecimal getNounloadGoodsQty() {
        return nounloadGoodsQty;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T_OPT_NOUNLOAD_GOODS_DETAIL.NOUNLOAD_GOODS_QTY
     *
     * @param nounloadGoodsQty the value for T_OPT_NOUNLOAD_GOODS_DETAIL.NOUNLOAD_GOODS_QTY
     *
     * @ibatorgenerated Wed Apr 16 14:27:54 CST 2014
     */
    public void setNounloadGoodsQty(BigDecimal nounloadGoodsQty) {
        this.nounloadGoodsQty = nounloadGoodsQty;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T_OPT_NOUNLOAD_GOODS_DETAIL.GOODS_WEIGHT_TOTAL
     *
     * @return the value of T_OPT_NOUNLOAD_GOODS_DETAIL.GOODS_WEIGHT_TOTAL
     *
     * @ibatorgenerated Wed Apr 16 14:27:54 CST 2014
     */
    public BigDecimal getGoodsWeightTotal() {
        return goodsWeightTotal;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T_OPT_NOUNLOAD_GOODS_DETAIL.GOODS_WEIGHT_TOTAL
     *
     * @param goodsWeightTotal the value for T_OPT_NOUNLOAD_GOODS_DETAIL.GOODS_WEIGHT_TOTAL
     *
     * @ibatorgenerated Wed Apr 16 14:27:54 CST 2014
     */
    public void setGoodsWeightTotal(BigDecimal goodsWeightTotal) {
        this.goodsWeightTotal = goodsWeightTotal;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T_OPT_NOUNLOAD_GOODS_DETAIL.GOODS_VOLUME_TOTAL
     *
     * @return the value of T_OPT_NOUNLOAD_GOODS_DETAIL.GOODS_VOLUME_TOTAL
     *
     * @ibatorgenerated Wed Apr 16 14:27:54 CST 2014
     */
    public BigDecimal getGoodsVolumeTotal() {
        return goodsVolumeTotal;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T_OPT_NOUNLOAD_GOODS_DETAIL.GOODS_VOLUME_TOTAL
     *
     * @param goodsVolumeTotal the value for T_OPT_NOUNLOAD_GOODS_DETAIL.GOODS_VOLUME_TOTAL
     *
     * @ibatorgenerated Wed Apr 16 14:27:54 CST 2014
     */
    public void setGoodsVolumeTotal(BigDecimal goodsVolumeTotal) {
        this.goodsVolumeTotal = goodsVolumeTotal;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T_OPT_NOUNLOAD_GOODS_DETAIL.NEXT_ORGNAME
     *
     * @return the value of T_OPT_NOUNLOAD_GOODS_DETAIL.NEXT_ORGNAME
     *
     * @ibatorgenerated Wed Apr 16 14:27:54 CST 2014
     */
    public String getNextOrgname() {
        return nextOrgname;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T_OPT_NOUNLOAD_GOODS_DETAIL.NEXT_ORGNAME
     *
     * @param nextOrgname the value for T_OPT_NOUNLOAD_GOODS_DETAIL.NEXT_ORGNAME
     *
     * @ibatorgenerated Wed Apr 16 14:27:54 CST 2014
     */
    public void setNextOrgname(String nextOrgname) {
        this.nextOrgname = nextOrgname;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T_OPT_NOUNLOAD_GOODS_DETAIL.UNLOAD_ORG_CODE
     *
     * @return the value of T_OPT_NOUNLOAD_GOODS_DETAIL.UNLOAD_ORG_CODE
     *
     * @ibatorgenerated Wed Apr 16 14:27:54 CST 2014
     */
    public String getUnloadOrgCode() {
        return unloadOrgCode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T_OPT_NOUNLOAD_GOODS_DETAIL.UNLOAD_ORG_CODE
     *
     * @param unloadOrgCode the value for T_OPT_NOUNLOAD_GOODS_DETAIL.UNLOAD_ORG_CODE
     *
     * @ibatorgenerated Wed Apr 16 14:27:54 CST 2014
     */
    public void setUnloadOrgCode(String unloadOrgCode) {
        this.unloadOrgCode = unloadOrgCode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T_OPT_NOUNLOAD_GOODS_DETAIL.PRODUCT_CODE
     *
     * @return the value of T_OPT_NOUNLOAD_GOODS_DETAIL.PRODUCT_CODE
     *
     * @ibatorgenerated Wed Apr 16 14:27:54 CST 2014
     */
    public String getProductCode() {
        return productCode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T_OPT_NOUNLOAD_GOODS_DETAIL.PRODUCT_CODE
     *
     * @param productCode the value for T_OPT_NOUNLOAD_GOODS_DETAIL.PRODUCT_CODE
     *
     * @ibatorgenerated Wed Apr 16 14:27:54 CST 2014
     */
    public void setProductCode(String productCode) {
        this.productCode = productCode;
    }

	public BigDecimal getGoodsWeightSum() {
		return goodsWeightSum;
	}

	public void setGoodsWeightSum(BigDecimal goodsWeightSum) {
		this.goodsWeightSum = goodsWeightSum;
	}

	public BigDecimal getGoodsVolumeSum() {
		return goodsVolumeSum;
	}

	public void setGoodsVolumeSum(BigDecimal goodsVolumeSum) {
		this.goodsVolumeSum = goodsVolumeSum;
	}
    
    
    
}