package com.deppon.foss.module.transfer.platform.api.shared.domain;

import java.math.BigDecimal;

public class StockSaturationReportEntity {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T_OPT_TMP_REPORT.ORG_CODE
     *
     * @ibatorgenerated Tue May 13 15:38:03 CST 2014
     */
    private String orgCode;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T_OPT_TMP_REPORT.ORG_NAME
     *
     * @ibatorgenerated Tue May 13 15:38:03 CST 2014
     */
    private String orgName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T_OPT_TMP_REPORT.PULLBACK_MONTH
     *
     * @ibatorgenerated Tue May 13 15:38:03 CST 2014
     */
    private BigDecimal pullbackMonth;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T_OPT_TMP_REPORT.PULLBACK_DAY
     *
     * @ibatorgenerated Tue May 13 15:38:03 CST 2014
     */
    private BigDecimal pullbackDay;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T_OPT_TMP_REPORT.SENDRATE_MONTH
     *
     * @ibatorgenerated Tue May 13 15:38:03 CST 2014
     */
    private BigDecimal sendrateMonth;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T_OPT_TMP_REPORT.SENDRATE_DAY
     *
     * @ibatorgenerated Tue May 13 15:38:03 CST 2014
     */
    private BigDecimal sendrateDay;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T_OPT_TMP_REPORT.RETURNDATE_MOTH
     *
     * @ibatorgenerated Tue May 13 15:38:03 CST 2014
     */
    private BigDecimal returndateMoth;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T_OPT_TMP_REPORT.RETURNDATE_DAY
     *
     * @ibatorgenerated Tue May 13 15:38:03 CST 2014
     */
    private BigDecimal returndateDay;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T_OPT_TMP_REPORT.SATURATION_DAY
     *
     * @ibatorgenerated Tue May 13 15:38:03 CST 2014
     */
    private BigDecimal saturationDay;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T_OPT_TMP_REPORT.SATURATION_MONTH
     *
     * @ibatorgenerated Tue May 13 15:38:03 CST 2014
     */
    private BigDecimal saturationMonth;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T_OPT_TMP_REPORT.DENSITY_DAY
     *
     * @ibatorgenerated Tue May 13 15:38:03 CST 2014
     */
    private BigDecimal densityDay;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T_OPT_TMP_REPORT.DENSITY_MONTH
     *
     * @ibatorgenerated Tue May 13 15:38:03 CST 2014
     */
    private BigDecimal densityMonth;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T_OPT_TMP_REPORT.QUERY_DATE_A
     *
     * @ibatorgenerated Tue May 13 15:38:03 CST 2014
     */
    private String queryDateA;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T_OPT_TMP_REPORT.QUERY_DATE_B
     *
     * @ibatorgenerated Tue May 13 15:38:03 CST 2014
     */
    private String queryDateB;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T_OPT_TMP_REPORT.BIGDEPT
     *
     * @ibatorgenerated Tue May 13 15:38:03 CST 2014
     */
    private String bigdept;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T_OPT_TMP_REPORT.DIVISION
     *
     * @ibatorgenerated Tue May 13 15:38:03 CST 2014
     */
    private String division;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T_OPT_TMP_REPORT.BIG_AREA
     *
     * @ibatorgenerated Tue May 13 15:38:03 CST 2014
     */
    private String bigArea;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T_OPT_TMP_REPORT.ORG_CODE
     *
     * @return the value of T_OPT_TMP_REPORT.ORG_CODE
     *
     * @ibatorgenerated Tue May 13 15:38:03 CST 2014
     */
    public String getOrgCode() {
        return orgCode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T_OPT_TMP_REPORT.ORG_CODE
     *
     * @param orgCode the value for T_OPT_TMP_REPORT.ORG_CODE
     *
     * @ibatorgenerated Tue May 13 15:38:03 CST 2014
     */
    public void setOrgCode(String orgCode) {
        this.orgCode = orgCode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T_OPT_TMP_REPORT.ORG_NAME
     *
     * @return the value of T_OPT_TMP_REPORT.ORG_NAME
     *
     * @ibatorgenerated Tue May 13 15:38:03 CST 2014
     */
    public String getOrgName() {
        return orgName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T_OPT_TMP_REPORT.ORG_NAME
     *
     * @param orgName the value for T_OPT_TMP_REPORT.ORG_NAME
     *
     * @ibatorgenerated Tue May 13 15:38:03 CST 2014
     */
    public void setOrgName(String orgName) {
        this.orgName = orgName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T_OPT_TMP_REPORT.PULLBACK_MONTH
     *
     * @return the value of T_OPT_TMP_REPORT.PULLBACK_MONTH
     *
     * @ibatorgenerated Tue May 13 15:38:03 CST 2014
     */
    public BigDecimal getPullbackMonth() {
        return pullbackMonth;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T_OPT_TMP_REPORT.PULLBACK_MONTH
     *
     * @param pullbackMonth the value for T_OPT_TMP_REPORT.PULLBACK_MONTH
     *
     * @ibatorgenerated Tue May 13 15:38:03 CST 2014
     */
    public void setPullbackMonth(BigDecimal pullbackMonth) {
        this.pullbackMonth = pullbackMonth;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T_OPT_TMP_REPORT.PULLBACK_DAY
     *
     * @return the value of T_OPT_TMP_REPORT.PULLBACK_DAY
     *
     * @ibatorgenerated Tue May 13 15:38:03 CST 2014
     */
    public BigDecimal getPullbackDay() {
        return pullbackDay;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T_OPT_TMP_REPORT.PULLBACK_DAY
     *
     * @param pullbackDay the value for T_OPT_TMP_REPORT.PULLBACK_DAY
     *
     * @ibatorgenerated Tue May 13 15:38:03 CST 2014
     */
    public void setPullbackDay(BigDecimal pullbackDay) {
        this.pullbackDay = pullbackDay;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T_OPT_TMP_REPORT.SENDRATE_MONTH
     *
     * @return the value of T_OPT_TMP_REPORT.SENDRATE_MONTH
     *
     * @ibatorgenerated Tue May 13 15:38:03 CST 2014
     */
    public BigDecimal getSendrateMonth() {
        return sendrateMonth;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T_OPT_TMP_REPORT.SENDRATE_MONTH
     *
     * @param sendrateMonth the value for T_OPT_TMP_REPORT.SENDRATE_MONTH
     *
     * @ibatorgenerated Tue May 13 15:38:03 CST 2014
     */
    public void setSendrateMonth(BigDecimal sendrateMonth) {
        this.sendrateMonth = sendrateMonth;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T_OPT_TMP_REPORT.SENDRATE_DAY
     *
     * @return the value of T_OPT_TMP_REPORT.SENDRATE_DAY
     *
     * @ibatorgenerated Tue May 13 15:38:03 CST 2014
     */
    public BigDecimal getSendrateDay() {
        return sendrateDay;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T_OPT_TMP_REPORT.SENDRATE_DAY
     *
     * @param sendrateDay the value for T_OPT_TMP_REPORT.SENDRATE_DAY
     *
     * @ibatorgenerated Tue May 13 15:38:03 CST 2014
     */
    public void setSendrateDay(BigDecimal sendrateDay) {
        this.sendrateDay = sendrateDay;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T_OPT_TMP_REPORT.RETURNDATE_MOTH
     *
     * @return the value of T_OPT_TMP_REPORT.RETURNDATE_MOTH
     *
     * @ibatorgenerated Tue May 13 15:38:03 CST 2014
     */
    public BigDecimal getReturndateMoth() {
        return returndateMoth;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T_OPT_TMP_REPORT.RETURNDATE_MOTH
     *
     * @param returndateMoth the value for T_OPT_TMP_REPORT.RETURNDATE_MOTH
     *
     * @ibatorgenerated Tue May 13 15:38:03 CST 2014
     */
    public void setReturndateMoth(BigDecimal returndateMoth) {
        this.returndateMoth = returndateMoth;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T_OPT_TMP_REPORT.RETURNDATE_DAY
     *
     * @return the value of T_OPT_TMP_REPORT.RETURNDATE_DAY
     *
     * @ibatorgenerated Tue May 13 15:38:03 CST 2014
     */
    public BigDecimal getReturndateDay() {
        return returndateDay;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T_OPT_TMP_REPORT.RETURNDATE_DAY
     *
     * @param returndateDay the value for T_OPT_TMP_REPORT.RETURNDATE_DAY
     *
     * @ibatorgenerated Tue May 13 15:38:03 CST 2014
     */
    public void setReturndateDay(BigDecimal returndateDay) {
        this.returndateDay = returndateDay;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T_OPT_TMP_REPORT.SATURATION_DAY
     *
     * @return the value of T_OPT_TMP_REPORT.SATURATION_DAY
     *
     * @ibatorgenerated Tue May 13 15:38:03 CST 2014
     */
    public BigDecimal getSaturationDay() {
        return saturationDay;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T_OPT_TMP_REPORT.SATURATION_DAY
     *
     * @param saturationDay the value for T_OPT_TMP_REPORT.SATURATION_DAY
     *
     * @ibatorgenerated Tue May 13 15:38:03 CST 2014
     */
    public void setSaturationDay(BigDecimal saturationDay) {
        this.saturationDay = saturationDay;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T_OPT_TMP_REPORT.SATURATION_MONTH
     *
     * @return the value of T_OPT_TMP_REPORT.SATURATION_MONTH
     *
     * @ibatorgenerated Tue May 13 15:38:03 CST 2014
     */
    public BigDecimal getSaturationMonth() {
        return saturationMonth;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T_OPT_TMP_REPORT.SATURATION_MONTH
     *
     * @param saturationMonth the value for T_OPT_TMP_REPORT.SATURATION_MONTH
     *
     * @ibatorgenerated Tue May 13 15:38:03 CST 2014
     */
    public void setSaturationMonth(BigDecimal saturationMonth) {
        this.saturationMonth = saturationMonth;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T_OPT_TMP_REPORT.DENSITY_DAY
     *
     * @return the value of T_OPT_TMP_REPORT.DENSITY_DAY
     *
     * @ibatorgenerated Tue May 13 15:38:03 CST 2014
     */
    public BigDecimal getDensityDay() {
        return densityDay;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T_OPT_TMP_REPORT.DENSITY_DAY
     *
     * @param densityDay the value for T_OPT_TMP_REPORT.DENSITY_DAY
     *
     * @ibatorgenerated Tue May 13 15:38:03 CST 2014
     */
    public void setDensityDay(BigDecimal densityDay) {
        this.densityDay = densityDay;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T_OPT_TMP_REPORT.DENSITY_MONTH
     *
     * @return the value of T_OPT_TMP_REPORT.DENSITY_MONTH
     *
     * @ibatorgenerated Tue May 13 15:38:03 CST 2014
     */
    public BigDecimal getDensityMonth() {
        return densityMonth;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T_OPT_TMP_REPORT.DENSITY_MONTH
     *
     * @param densityMonth the value for T_OPT_TMP_REPORT.DENSITY_MONTH
     *
     * @ibatorgenerated Tue May 13 15:38:03 CST 2014
     */
    public void setDensityMonth(BigDecimal densityMonth) {
        this.densityMonth = densityMonth;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T_OPT_TMP_REPORT.QUERY_DATE_A
     *
     * @return the value of T_OPT_TMP_REPORT.QUERY_DATE_A
     *
     * @ibatorgenerated Tue May 13 15:38:03 CST 2014
     */
    public String getQueryDateA() {
        return queryDateA;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T_OPT_TMP_REPORT.QUERY_DATE_A
     *
     * @param queryDateA the value for T_OPT_TMP_REPORT.QUERY_DATE_A
     *
     * @ibatorgenerated Tue May 13 15:38:03 CST 2014
     */
    public void setQueryDateA(String queryDateA) {
        this.queryDateA = queryDateA;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T_OPT_TMP_REPORT.QUERY_DATE_B
     *
     * @return the value of T_OPT_TMP_REPORT.QUERY_DATE_B
     *
     * @ibatorgenerated Tue May 13 15:38:03 CST 2014
     */
    public String getQueryDateB() {
        return queryDateB;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T_OPT_TMP_REPORT.QUERY_DATE_B
     *
     * @param queryDateB the value for T_OPT_TMP_REPORT.QUERY_DATE_B
     *
     * @ibatorgenerated Tue May 13 15:38:03 CST 2014
     */
    public void setQueryDateB(String queryDateB) {
        this.queryDateB = queryDateB;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T_OPT_TMP_REPORT.BIGDEPT
     *
     * @return the value of T_OPT_TMP_REPORT.BIGDEPT
     *
     * @ibatorgenerated Tue May 13 15:38:03 CST 2014
     */
    public String getBigdept() {
        return bigdept;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T_OPT_TMP_REPORT.BIGDEPT
     *
     * @param bigdept the value for T_OPT_TMP_REPORT.BIGDEPT
     *
     * @ibatorgenerated Tue May 13 15:38:03 CST 2014
     */
    public void setBigdept(String bigdept) {
        this.bigdept = bigdept;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T_OPT_TMP_REPORT.DIVISION
     *
     * @return the value of T_OPT_TMP_REPORT.DIVISION
     *
     * @ibatorgenerated Tue May 13 15:38:03 CST 2014
     */
    public String getDivision() {
        return division;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T_OPT_TMP_REPORT.DIVISION
     *
     * @param division the value for T_OPT_TMP_REPORT.DIVISION
     *
     * @ibatorgenerated Tue May 13 15:38:03 CST 2014
     */
    public void setDivision(String division) {
        this.division = division;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T_OPT_TMP_REPORT.BIG_AREA
     *
     * @return the value of T_OPT_TMP_REPORT.BIG_AREA
     *
     * @ibatorgenerated Tue May 13 15:38:03 CST 2014
     */
    public String getBigArea() {
        return bigArea;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T_OPT_TMP_REPORT.BIG_AREA
     *
     * @param bigArea the value for T_OPT_TMP_REPORT.BIG_AREA
     *
     * @ibatorgenerated Tue May 13 15:38:03 CST 2014
     */
    public void setBigArea(String bigArea) {
        this.bigArea = bigArea;
    }
}