/*package com.deppon.itsm.module.remote.foss.server.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

*//**
 * This class was generated by Apache CXF 2.6.3
 * 2013-11-14T09:46:21.890+08:00
 * Generated source version: 2.6.3
 * 
 *//*
@WebServiceClient(name = "IAutomaticReportServiceService", 
                  wsdlLocation = "file:/D:/技术学习/ESB/wsdl-validate/src/main/itsm/itsm-foss.wsdl",
                  targetNamespace = "http://service.server.foss.remote.module.itsm.deppon.com/") 
public class IAutomaticReportServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.server.foss.remote.module.itsm.deppon.com/", "IAutomaticReportServiceService");
    public final static QName IAutomaticReportServicePort = new QName("http://service.server.foss.remote.module.itsm.deppon.com/", "IAutomaticReportServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/技术学习/ESB/wsdl-validate/src/main/itsm/itsm-foss.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(IAutomaticReportServiceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/D:/技术学习/ESB/wsdl-validate/src/main/itsm/itsm-foss.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public IAutomaticReportServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public IAutomaticReportServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IAutomaticReportServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    *//**
     *
     * @return
     *     returns IAutomaticReportService
     *//*
    @WebEndpoint(name = "IAutomaticReportServicePort")
    public UpdateOrderItem getIAutomaticReportServicePort() {
        return super.getPort(IAutomaticReportServicePort, UpdateOrderItem.class);
    }

    *//**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IAutomaticReportService
     *//*
    @WebEndpoint(name = "IAutomaticReportServicePort")
    public UpdateOrderItem getIAutomaticReportServicePort(WebServiceFeature... features) {
        return super.getPort(IAutomaticReportServicePort, UpdateOrderItem.class, features);
    }

}
*/