package com.deppon.itsm.module.remote.foss.server.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by Apache CXF 2.6.3
 * 2013-11-14T09:46:21.734+08:00
 * Generated source version: 2.6.3
 * 
 */
@WebService(targetNamespace = "http://webservice.shpy.com/", name = "UpdateOrderItem2")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface UpdateOrderItem2 {

    @WebResult(name = "return", targetNamespace = "http://webservice.shpy.com/", partName = "return")
    @WebMethod
    public java.lang.String automaticReportQuestion(
        @WebParam(partName = "questions", name = "questions")
        java.lang.String questions
    );
}
