CREATE OR REPLACE VIEW V_STL_DVD_NRFDO AS
SELECT BUSINESS_CASE,
			 CUSTOMER_CODE,
			 CUSTOMER_NAME,
			 CUSTOMER_TYPE,
			 ORIG_ORG_CODE,
			 ORIG_ORG_NAME,
			 DEST_ORG_CODE,
			 DEST_ORG_NAME,
			 WAYBILL_NO,
			 BILL_NO,
			 ACCOUNT_DATE,
			 BUSINESS_DATE,
			 BILL_PARENT_TYPE,
			 BILL_TYPE,
			 AMOUNT,
			 AMOUNT_FRT,
			 AMOUNT_PUP,
			 AMOUNT_DEL,
			 AMOUNT_PKG,
			 AMOUNT_DV,
			 AMOUNT_COD,
			 AMOUNT_OT,
			 PRODUCT_CODE,
			 ID,
			 PERIOD
	FROM STV.T_STL_NDVD T
 WHERE T.BUSINESS_CASE IN
			 ('CUST_DRO_WO_DEST_RCVT_PODD',
				'RD_DESTO_DEST_RCVO_PODP',
				'RD_DESTO_WO_DEST_RCVT_NPODP',
				'CUST_DRO_WO_DEST_RCVT_NPODD',
				'CLAIM_DESTO_WO_DEST_RCVO_PODP',
				'RD_DESTO_PAY_APPLY',
				'RD_DESTO_WO_DEST_RCVO_NPODP',
				'CLAIM_DESTO_WO_DEST_RCVO_NPODP',
				'CUST_DRO_WO_DEST_RCVO_PODD',
				'RD_DESTO_DEST_RCVT_PODP',
				'RD_DESTO_INCOME',
				'CLAIM_DESTO_PAY_APPLY',
				'CUST_DRO_WO_DEST_RCVO_NPODD',
				'CLAIM_DESTO_COST',
				'CLAIM_DESTO_WO_DEST_RCVT_NPODP',
				'RD_DESTO_COST',
				'CPO_DEST_PAY_APPLY',
				'CLAIM_DESTO_INCOME',
				'CLAIM_DESTO_WO_DEST_RCVT_PODP')
			 AND T.PRODUCT_CODE IN ('FLF', --精准卡航
															'FSF', --精准城运
															'LRF', --精准汽运(长途)
															'SRF', --精准汽运(短途)
															'WVH', --整车
															'PACKAGE' --快递包裹
															)


WITH READ ONLY
;
