CREATE OR REPLACE VIEW V_STL_DVD_NPLI AS
SELECT BUSINESS_CASE,
			 CUSTOMER_CODE,
			 CUSTOMER_NAME,
			 CUSTOMER_TYPE,
			 WAYBILL_NO,
			 BILL_NO,
			 ACCOUNT_DATE,
			 BUSINESS_DATE,
			 BILL_PARENT_TYPE,
			 BILL_TYPE,
			 AMOUNT,
			 PRODUCT_CODE,
			 ID,
			 PERIOD,
			 CREDIT_ORG_CODE,
			 CREDIT_ORG_NAME,
			 CREDIT_INVOICE_MARK,
       CREDIT_ORG_TYPE,
			 DEBIT_ORG_CODE,
			 DEBIT_ORG_NAME,
			 DEBIT_INVOICE_MARK,
       DEBIT_ORG_TYPE
	FROM STV.T_STL_NDVDI T
 WHERE T.BUSINESS_CASE IN ('PL_COST_WO_DEST_RCVT_POD',
													 'PL_DR_WO_DEST_RCVT_POD',
													 'PL_COST_WO_DEST_RCVO_POD',
													 'PL_COST_WO_DEST_RCVT_NPOD',
													 'PL_DR_WO_DEST_RCVT_NPOD',
													 'UROP_DEST_CH_POD',
													 'URTP_DEST_CD_NPOD',
													 'UROP_DEST_CD_NPOD',
													 'URTP_DEST_CH_NPOD',
													 'UROP_DEST_CD_POD',
													 'UROP_DEST_CH_NPOD',
													 'PL_DR_WO_DEST_RCVO_POD',
													 'URTP_DEST_CD_POD',
													 'PL_DR_WO_DEST_RCVO_NPOD',
													 'URTP_DEST_CH_POD',
													 'PL_COST_WO_DEST_RCVO_NPOD',
                           'POP_WO_DRO_POD',
                           'POP_WO_DRO_NPOD',
                           'POP_WO_DRT_POD',
                           'POP_WO_DRT_NPOD')
WITH READ ONLY;
