CREATE OR REPLACE VIEW V_STL_DVD_NRFOSO AS

--01����ʼ���±���

SELECT BUSINESS_CASE,
			 CUSTOMER_CODE,
			 CUSTOMER_NAME,
			 CUSTOMER_TYPE,
			 ORIG_ORG_CODE,
			 ORIG_ORG_NAME,
			 DEST_ORG_CODE,
			 DEST_ORG_NAME,
			 WAYBILL_NO,
			 BILL_NO,
			 ACCOUNT_DATE,
			 BUSINESS_DATE,
			 BILL_PARENT_TYPE,
			 BILL_TYPE,
			 AMOUNT,
			 AMOUNT_FRT,
			 AMOUNT_PUP,
			 AMOUNT_DEL,
			 AMOUNT_PKG,
			 AMOUNT_DV,
			 AMOUNT_COD,
			 AMOUNT_OT,
			 PRODUCT_CODE,
			 ID,
			 PERIOD
	FROM STV.T_STL_NDVD T
 WHERE T.BUSINESS_CASE IN ('CLAIM_DESTT_WO_DEST_RCVO_POD',
													 'EX_ORIG_RCVO_POD',
													 'OR_CLAIM_PAYO_WO_RCVTP',
													 'RD_DESTO_DEST_RCVO_POD',
													 'RD_ORIGO_WO_ORIG_RCVO_POD',
													 'AC_CASHO',
													 'CLAIM_ORIGO_COST',
													 'CPO_ORIG_PAY_APPLY',
													 'EX_DEST_RCVO_POD',
													 'OR_CLAIM_PAYO_WO_RCVO',
													 'OR_CLAIM_PAYT_WO_RCVO',
													 'RD_ORIGO_COST',
													 'SFO_PAY_APPLY',
													 'AC_ORIG_RCV_NWOO',
													 'BD_WO_DEST_RCVO_POD',
													 'CLAIM_DESTO_WO_DEST_RCVO_POD',
													 'CLAIM_DESTT_WO_DEST_RCVO_NPOD',
													 'CLAIM_ORIGO_WO_ORIG_RCVO_POD',
													 'OR_CH_UR_RCVO',
													 'OR_CUST_DRT_WO_RCVO',
													 'RD_DESTO_WO_DEST_RCVO_NPOD',
													 'RD_ORIGT_WO_ORIG_RCVO_NPOD',
													 'CLAIM_DESTO_WO_DEST_RCVO_NPOD',
													 'CLAIM_ORIGO_INCOME',
													 'OR_CH_PBIO',
													 'OR_RCVO_PBI',
													 'RD_DESTO_INCOME',
													 'RD_DESTT_WO_DEST_RCVO_POD',
													 'RD_ORIGO_PAY_APPLY',
													 'RD_ORIGO_WO_ORIG_RCVO_NPOD',
													 'CLAIM_ORIGO_PAY_APPLY',
													 'CLAIM_ORIGO_WO_ORIG_RCVT_PODP',
													 'OR_BAD_WO_RCVO',
													 'AC_ORIG_RCV_WOO',
													 'OR_CD_UR_RCVO',
													 'OR_CUST_DRO_WO_RCVTD',
													 'RD_DESTT_WO_DEST_RCVO_NPOD',
													 'RD_ORIGO_INCOME',
													 'RD_ORIGO_WO_ORIG_RCVT_PODP',
													 'CLAIM_ORIGO_ORIG_RCVO_NPOD',
													 'CLAIM_ORIGO_WO_ORIG_RCVT_NPODP',
													 'CLAIM_ORIGT_WO_ORIG_RCVO_NPOD',
													 'OR_CD_PBIO',
													 'OR_COD_PAY_WO_RCVO',
													 'OR_EX_WO_RCVO',
													 'RD_ORIGT_WO_ORIG_RCVO_POD',
													 'BD_WO_ORIG_RCVO_POD',
													 'CLAIM_DESTO_INCOME',
													 'CLAIM_ORIGT_ORIG_RCVO_POD',
													 'OR_CUST_DRO_WO_RCVO',
													 'RD_ORIGO_WO_ORIG_RCVT_NPODP')

WITH READ ONLY;
