CREATE OR REPLACE VIEW V_STL_DVD_NRFONT AS

--02普通始发月报表

SELECT BUSINESS_CASE,
       CUSTOMER_CODE,
       CUSTOMER_NAME,
       CUSTOMER_TYPE,
       ORIG_ORG_CODE,
       ORIG_ORG_NAME,
       DEST_ORG_CODE,
       DEST_ORG_NAME,
       WAYBILL_NO,
       BILL_NO,
       ACCOUNT_DATE,
       BUSINESS_DATE,
       BILL_PARENT_TYPE,
       BILL_TYPE,
       AMOUNT,
       AMOUNT_FRT,
       AMOUNT_PUP,
       AMOUNT_DEL,
       AMOUNT_PKG,
       AMOUNT_DV,
       AMOUNT_COD,
       AMOUNT_OT,
       PRODUCT_CODE,
       ID,
       PERIOD
  FROM STV.T_STL_NDVD T
 WHERE T.BUSINESS_CASE IN ('AL_DR_WO_DEST_RCVT_NPOD',
                           'COD_PAY_WO_ORIG_RCVT_NPOD',
                           'CUST_DRO_WO_DEST_RCVT_POD',
                           'CUST_DRT_WO_ORIG_RCVO_NPODD',
                           'CUST_DRT_WO_ORIG_RCVT_NPOD',
                           'DET_CH',
                           'PL_COST_WO_DEST_RCVT_POD',
                           'PL_DR_WO_DEST_RCVT_POD',
                           'URO_ORIG_CD_NPOD',
                           'URO_ORIG_CD_POD',
                           'URT_DEST_CD_PODO',
                           'ALPWR_WO_DEST_RCVT_POD',
                           'COD_PAY_WO_DEST_RCVT_POD',
                           'CUST_DRO_WO_DEST_RCVT_NPOD',
                           'CUST_DRT_PAY_APPLY',
                           'CUST_DRT_WO_DEST_RCVT_POD',
                           'PL_COST_WO_DEST_RCVT_NPOD',
                           'PL_DR_WO_DEST_RCVT_NPOD',
                           'PODT_ORIG_RCV_NWO',
                           'UPDT_CASH_COLLECTED',
                           'CUST_DRO_WO_ORIG_RCVT_POD',
                           'OTH_PAY_WO_DEST_RCVT_NPOD',
                           'UPDT_DEST_RCV_NWO',
                           'URT_DEST_CD_NPODO',
                           'COD_PAY_WO_ORIG_RCVT_POD',
                           'CUST_DRT_WO_ORIG_RCVT_POD',
                           'DET_CD',
                           'URT_DEST_CH_NPODO',
                           'URT_ORIG_CH_NPOD',
                           'AL_DR_WO_DEST_RCVT_POD',
                           'CUST_DR_TCH',
                           'PODT_CASH_COLLECTED',
                           'PODT_DEST_RCV_WO',
                           'UPDT_ORIG_RCV_WO',
                           'CUST_DRT_WO_DEST_RCVT_NPOD',
                           'CUST_DRT_WO_ORIG_RCVO_PODD',
                           'CUST_DR_OCD',
                           'URT_ORIG_CD_NPOD',
                           'ALPWR_WO_DEST_RCVT_NPOD',
                           'CUST_DRO_PAY_APPLY',
                           'CUST_DR_OCH',
                           'CUST_DR_TCD',
                           'DEO_CH',
                           'PODT_DEST_RCV_NWO',
                           'UPDT_DEST_RCV_WO',
                           'URT_DEST_CH_PODO',
                           'COD_PAY_WO_DEST_RCVT_NPOD',
                           'CUST_DRO_WO_ORIG_RCVT_NPOD',
                           'DEO_CD',
                           'OTH_PAY_WO_DEST_RCVT_POD',
                           'PODT_ORIG_RCV_WO',
                           'UPDT_ORIG_RCV_NWO',
                           'URO_ORIG_CH_NPOD',
                           'URO_ORIG_CH_POD',
                           'URT_ORIG_CD_POD',
                           'URT_ORIG_CH_POD')
                           
WITH READ ONLY;
