CREATE OR REPLACE VIEW V_STL_DVD_NPLR AS
SELECT BUSINESS_CASE,
       CUSTOMER_CODE,
       CUSTOMER_NAME,
       CUSTOMER_TYPE,
       ORIG_ORG_CODE,
       ORIG_ORG_NAME,
       DEST_ORG_CODE,
       DEST_ORG_NAME,
       WAYBILL_NO,
       BILL_NO,
       ACCOUNT_DATE,
       BUSINESS_DATE,
       BILL_PARENT_TYPE,
       BILL_TYPE,
       AMOUNT,
       AMOUNT_FRT,
       AMOUNT_PUP,
       AMOUNT_DEL,
       AMOUNT_PKG,
       AMOUNT_DV,
       AMOUNT_COD,
       AMOUNT_OT,
       PRODUCT_CODE,
       ID,
       PERIOD
  FROM STV.T_STL_NDVD T
 WHERE T.BUSINESS_CASE IN ('PL_COST_WO_DEST_RCVT_PODP',
                           'PL_DR_WO_DEST_RCVT_PODD',
                           'PL_COST_CONFIRM',
                           'PL_COST_ENTRY',
                           'PL_COST_PAY_APPLY',
                           'PL_COST_WO_DEST_RCVO_PODP',
                           'PL_COST_WO_DEST_RCVT_NPODP',
                           'PL_DR_WO_DEST_RCVT_NPODD',
                           'UROP_DEST_CH_POD',
                           'URTP_DEST_CD_NPOD',
                           'UROP_DEST_CD_NPOD',
                           'URTP_DEST_CH_NPOD',
                           'UROP_DEST_CD_POD',
                           'UROP_DEST_CH_NPOD',
                           'PL_DR_CD',
                           'PL_DR_WO_DEST_RCVO_PODD',
                           'URTP_DEST_CD_POD',
                           'PL_COST_NCONFIRM',
                           'PL_DR_CH',
                           'PL_DR_PAY_APPLY',
                           'PL_DR_WO_DEST_RCVO_NPODD',
                           'URTP_DEST_CH_POD',
                           'PL_COST_WO_DEST_RCVO_NPODP',
                           'PL_COST_OP_CRM',
                           'PL_DR_WO_OR',
                           'POR_ENTRY',
                           'UR_POR_CH',
                           'UR_POR_CD',
                           'POP_WO_DRO_POD',
                           'POP_WO_DRO_NPOD',
                           'POP_WO_DRT_POD',
                           'POP_WO_DRT_NPOD',
                           'POCP_WO_OR')
       AND T.PRODUCT_CODE = 'PLF' --ÆûÔËÆ«Ïß
WITH READ ONLY
;
