CREATE OR REPLACE VIEW V_STL_DVD_NAFI AS
SELECT BUSINESS_CASE,
			 CUSTOMER_CODE,
			 CUSTOMER_NAME,
			 CUSTOMER_TYPE,
			 WAYBILL_NO,
			 BILL_NO,
			 ACCOUNT_DATE,
			 BUSINESS_DATE,
			 BILL_PARENT_TYPE,
			 BILL_TYPE,
			 AMOUNT,
			 PRODUCT_CODE,
			 ID,
			 PERIOD,
			 CREDIT_ORG_CODE,
			 CREDIT_ORG_NAME,
			 CREDIT_INVOICE_MARK,
       CREDIT_ORG_TYPE,
			 DEBIT_ORG_CODE,
			 DEBIT_ORG_NAME,
			 DEBIT_INVOICE_MARK,
       DEBIT_ORG_TYPE
	FROM STV.T_STL_NDVDI T
 WHERE T.BUSINESS_CASE IN ('APWR_COST_WO_DEST_RCVT_NPOD',
													 'APWR_OTH_PAY_WO_DEST_RCVT_POD',
													 'URTA_DEST_CH_POD',
													 'AIR_COD_CH_UR_POD',
													 'AIR_COD_POD_WO',
													 'AIR_COD_UPD_NWO',
													 'AIR_COD_UPD_WO',
													 'AIR_DR_WO_DEST_RCVT_NPOD',
													 'APWR_OTH_PAY_WO_DEST_RCVO_POD',
													 'URTA_DEST_CD_NPOD',
													 'URTA_DEST_CD_POD',
													 'AIR_COD_DPAY_WO_COD_RCV_POD',
													 'AIR_DR_WO_DEST_RCVO_POD',
													 'APWR_COST_WO_DEST_RCVO_POD',
													 'URTA_DEST_CH_NPOD',
													 'APWR_COST_WO_DEST_RCVT_POD',
													 'UROA_DEST_CH_NPOD',
													 'AIR_COD_CD_UR_POD',
													 'AIR_COD_POD_NWO',
													 'APWR_OTH_PAY_WO_DEST_RCVO_NPOD',
													 'AIR_DR_WO_DEST_RCVT_POD',
													 'APWR_OTH_PAY_WO_DEST_RCVT_NPOD',
													 'UROA_DEST_CD_POD',
													 'UROA_DEST_CH_POD',
													 'AIR_COD_OTH_PAY_WO_COD_RCV_POD',
													 'AIR_DR_WO_COD_RCV_POD',
													 'AIR_DR_WO_DEST_RCVO_NPOD',
													 'APWR_COST_WO_DEST_RCVO_NPOD',
													 'UROA_DEST_CD_NPOD')


WITH READ ONLY;
