CREATE TABLE STV.T_STL_MVR_INOVICE_MARK_INIT
(
       \*
       * 应收单：YS,现金收款单:XS,小票:OR
       *\
       PARENT_TYPE VARCHAR2(10) NOT NULL,
       BILL_NO VARCHAR2(50) NOT NULL,
       BILL_TYPE VARCHAR2(10)
);

--初始化脚本
DECLARE

	CURSOR CUR_DATA IS
		SELECT * FROM STV.T_STL_MVR_INOVICE_MARK_INIT;

	PARENT_TYPE_RCV  CHAR(2) := 'YS';
	PARENT_TYPE_CASH CHAR(2) := 'XS';
	PARENT_TYPE_OR   CHAR(2) := 'OR';

	V_UPDATE_ROWS INT := 0;

BEGIN

	FOR V_DATA IN CUR_DATA LOOP
	
		--应收单
		IF V_DATA.PARENT_TYPE = PARENT_TYPE_RCV THEN
		
			UPDATE STL.T_STL_BILL_RECEIVABLE RCV
				 SET RCV.INVOICE_MARK = 'INVOICE_TYPE_01'
			 WHERE RCV.WAYBILL_NO = V_DATA.BILL_NO
						 AND RCV.BILL_TYPE = V_DATA.BILL_TYPE;
		
			--现金收款单
		ELSIF V_DATA.PARENT_TYPE = PARENT_TYPE_CASH THEN
		
			UPDATE STL.T_STL_BILL_CASH_COLLECTION CASH
				 SET CASH.INVOICE_MARK = 'INVOICE_TYPE_01'
			 WHERE CASH.WAYBILL_NO = V_DATA.BILL_NO;
		
			--小票
		ELSIF V_DATA.PARENT_TYPE = PARENT_TYPE_OR THEN
		
			--更新小票应收
			UPDATE STL.T_STL_BILL_RECEIVABLE RCV
				 SET RCV.INVOICE_MARK = 'INVOICE_TYPE_01'
			 WHERE RCV.BILL_TYPE = 'RR'
						 AND RCV.SOURCE_BILL_TYPE = 'R'
						 AND RCV.SOURCE_BILL_NO = V_DATA.BILL_NO;
		
			UPDATE STL.T_STL_OTHER_REVENUE ORE
				 SET ORE.INVOICE_MARK = 'INVOICE_TYPE_01'
			 WHERE ORE.OTHER_REVENUE_NO = V_DATA.BILL_NO;
		
		END IF;
	
		V_UPDATE_ROWS := V_UPDATE_ROWS + 1;
		IF V_UPDATE_ROWS >= 10000 THEN
			COMMIT;
			V_UPDATE_ROWS := 0;
		END IF;
	
		COMMIT;
	
	END LOOP;

END;
