--02特殊业务始发月报表增加3列
ALTER TABLE STV.T_STL_MVR_NRFOST
ADD (
    OR_CH_RENT_INCOME NUMBER(18) DEFAULT 0, /*小票现金之富余仓库出租收入*/
    OR_CH_BANK_INT NUMBER(18) DEFAULT 0, /*小票现金之收银员卡利息*/
    OR_CD_RENT_INCOME NUMBER(18) DEFAULT 0
);

COMMENT ON COLUMN STV.T_STL_MVR_NRFOST.OR_CH_RENT_INCOME IS '小票现金之富余仓库出租收入';
COMMENT ON COLUMN STV.T_STL_MVR_NRFOST.OR_CH_BANK_INT IS '小票现金之收银员卡利息';
COMMENT ON COLUMN STV.T_STL_MVR_NRFOST.OR_CD_RENT_INCOME IS '小票银行之富余仓库出租收入';
