DECLARE

	--定义数据模型
	TYPE DATA_RECORD IS RECORD(
		WAYBILL_NO VARCHAR2(50),
		BILL_TYPE  VARCHAR2(10));

	--应收单数据行
	RCV_RECORD DATA_RECORD;

	--定义应收单数据集合
	TYPE RCV_RECORD_ARRAY IS TABLE OF RCV_RECORD%TYPE INDEX BY BINARY_INTEGER;

	RCV_RECORDS           RCV_RECORD_ARRAY;
	V_RCV_AMOUNT          STL.T_STL_BILL_RECEIVABLE.AMOUNT%TYPE;
	V_RCV_VERIFY_AMOUNT   STL.T_STL_BILL_RECEIVABLE.VERIFY_AMOUNT%TYPE;
	V_RCV_UNVERIFY_AMOUNT STL.T_STL_BILL_RECEIVABLE.UNVERIFY_AMOUNT%TYPE;
	V_RCV_CONREVEN_DATE   STL.T_STL_BILL_RECEIVABLE.CONREVEN_DATE%TYPE;

BEGIN

	--插入数据
	RCV_RECORD.WAYBILL_NO := '12345678';
	RCV_RECORD.BILL_TYPE := 'CT';
	RCV_RECORDS(1) := RCV_RECORD;

	RCV_RECORD.WAYBILL_NO := 'ABCDEFGH';
	RCV_RECORD.BILL_TYPE := 'DT';
	RCV_RECORDS(2) := RCV_RECORD;

	FOR I IN 1 .. RCV_RECORDS.COUNT LOOP
	
		BEGIN
			SELECT RCV.AMOUNT,
						 RCV.VERIFY_AMOUNT,
						 RCV.UNVERIFY_AMOUNT,
						 RCV.CONREVEN_DATE
				INTO V_RCV_AMOUNT,
						 V_RCV_VERIFY_AMOUNT,
						 V_RCV_UNVERIFY_AMOUNT,
						 V_RCV_CONREVEN_DATE
				FROM STL.T_STL_BILL_RECEIVABLE RCV
			 WHERE RCV.WAYBILL_NO = RCV_RECORDS(I).WAYBILL_NO
						 AND RCV.BILL_TYPE = RCV_RECORDS(I).BILL_TYPE
						 AND RCV.ACTIVE = 'Y';
		
			IF ((V_RCV_CONREVEN_DATE IS NOT NULL AND V_RCV_VERIFY_AMOUNT = 0) OR
				 (V_RCV_CONREVEN_DATE IS NULL AND V_RCV_UNVERIFY_AMOUNT = 0) OR
				 (V_RCV_CONREVEN_DATE IS NULL AND V_RCV_VERIFY_AMOUNT = 0)) THEN
			
				UPDATE STL.T_STL_BILL_RECEIVABLE RCV
					 SET RCV.INVOICE_MARK = 'INVOICE_TYPE_01'
				 WHERE RCV.WAYBILL_NO = RCV_RECORDS(I).WAYBILL_NO
							 AND RCV.BILL_TYPE = RCV_RECORDS(I).BILL_TYPE;
			
				COMMIT;
			
			END IF;
		
		EXCEPTION
			WHEN NO_DATA_FOUND THEN
				NULL;
		END;
	END LOOP;

END;
